definitions:
  request.HelloBodyRequest:
    properties:
      content:
        example: This content
        type: string
      title:
        example: This title
        type: string
    required:
    - content
    - title
    type: object
info:
  contact: {}
paths:
  /api/v1/hello:
    get:
      consumes:
      - application/json
      description: Return hello From Server
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Helo endpoint
      tags:
      - Example
  /api/v1/hello-body:
    post:
      consumes:
      - application/json
      description: Return message from server
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.HelloBodyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Send message via body
      tags:
      - Example
  /api/v1/hello-form-data:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Return message from server
      parameters:
      - description: title
        in: formData
        name: title
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Send message via form data
      tags:
      - Example
  /api/v1/hello-query:
    get:
      consumes:
      - application/json
      description: Send the query and return message from server
      parameters:
      - description: title
        in: query
        name: title
        type: string
      - description: content
        in: query
        name: content
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Hello from query
      tags:
      - Example
swagger: "2.0"
